FROM postgres:11
LABEL maintainer="M. Edward (Ed) Borasky <ed.borasky@hackoregon.org>"

# Install apt packages
RUN apt-get update \
  && apt-get install -qqy --no-install-recommends \
    postgresql-11-postgis-2.5 \
    postgresql-11-postgis-2.5-scripts \
  && apt-get clean

# set up automatic restores
COPY postgis-scripts/1make-dbusers.sh Backups/restore-all.sh /docker-entrypoint-initdb.d/
COPY Backups /Backups
