---
title: "Bus travelshed data extraction"
output: html_notebook
---

## Libraries
```{r}
library(data.table)
library(lubridate)
library(DT)

```

## Functions
```{r}
## quarter hour of day
qhod <- function(tstamp) {
  0.25 * trunc(4 * hour(tstamp) + minute(tstamp) / 15)
}

# cleaned quantiles
qx <- function(x, p) {
    quantile(
      x, probs = p, na.rm = TRUE, names = FALSE
    )
}

```

## Vehicle stop history
Note: because this has to run in an 8GB laptop, we garbage-collect frequently
and avoid chaining / pipes.
```{r}
bus_passenger_stops <- fread("/csvs/raw_veh_stoph_2017_09.csv")
gc()
bus_passenger_stops <- bus_passenger_stops[
  !is.na(NOM_ARR_TIME) &
  !is.na(NOM_DEP_TIME) &
  !is.na(STOP_ID) &
  !is.na(GPS_LONGITUDE) &
  !is.na(GPS_LATITUDE) &
  GPS_LONGITUDE > -124 & GPS_LONGITUDE < -121 &
  GPS_LATITUDE > 44 & GPS_LATITUDE < 46
]
gc()

```

## Stop events
```{r}
stop_events <- fread("/csvs/raw_stop_event_2017_09.csv")
gc()
stop_events <- stop_events[
  ROUTE_NUMBER >= 1 &
  ROUTE_NUMBER <= 291,
  .(SERVICE_DATE, VEHICLE_NUMBER, ROUTE_NUMBER, DIRECTION, SERVICE_KEY, DWELL,
    LOCATION_ID, ARRIVE_TIME, LEAVE_TIME, DOOR, LIFT, ONS, OFFS, ESTIMATED_LOAD)
]
gc()

```

## Join the tables to get bus passenger stops
```{r}
bus_passenger_stops_by <- c(
  "OPD_DATE",
  "VEHICLE_ID",
  "ACT_ARR_TIME",
  "ACT_DEP_TIME",
  "STOP_ID"
)
setkeyv(bus_passenger_stops, bus_passenger_stops_by)
gc()
stop_events_by <- c(
  "SERVICE_DATE",
  "VEHICLE_NUMBER",
  "ARRIVE_TIME",
  "LEAVE_TIME",
  "LOCATION_ID"
)
setkeyv(stop_events, stop_events_by)
gc()
bus_passenger_stops <- merge(
  bus_passenger_stops, stop_events,
  by.x = bus_passenger_stops_by, by.y = stop_events_by,
  all = FALSE
)
rm(stop_events, stop_events_by)
gc()

```

## Date computations
```{r}
bus_passenger_stops <- bus_passenger_stops[
  , OPD_DATE := fast_strptime(
    OPD_DATE, format = "%d%b%Y:%H:%M:%S", tz = "PST8PDT", lt = FALSE
  )
]
gc()
bus_passenger_stops <- bus_passenger_stops[
  , `:=`(
    NOM_ARR_TIME = OPD_DATE + NOM_ARR_TIME,
    ACT_ARR_TIME = OPD_DATE + ACT_ARR_TIME,
    NOM_DEP_TIME = OPD_DATE + NOM_DEP_TIME,
    ACT_DEP_TIME = OPD_DATE + ACT_DEP_TIME,
    YEAR = year(OPD_DATE),
    MONTH = month(OPD_DATE),
    DAY = mday(OPD_DATE),
    DAY_OF_WEEK = wday(OPD_DATE)
  )
]
gc()
bus_passenger_stops <- bus_passenger_stops[
  , QHOUR_OF_DAY := qhod(ACT_ARR_TIME)
]
gc()

```

## Lagged columns
```{r}
bus_passenger_stops_by <- c(
  "VEHICLE_ID",
  "ACT_ARR_TIME",
  "ACT_DEP_TIME",
  "STOP_ID"
)
setkeyv(bus_passenger_stops, bus_passenger_stops_by)
bus_passenger_stops <- bus_passenger_stops[
  , `:=`(
    FROM_STOP = shift(STOP_ID),
    DISTANCE_METERS = METERS - shift(METERS),
    SECONDS_BETWEEN_STOPS = as.integer(ACT_ARR_TIME - shift(ACT_ARR_TIME)),
    SECONDS_LATE = as.integer(ACT_ARR_TIME - NOM_ARR_TIME)
  ),
  by = EVENT_NO_TRIP
]
gc()
bus_passenger_stops <- bus_passenger_stops[!is.na(FROM_STOP)]

```
## summary
```{r}
bus_passenger_stops_summary <- bus_passenger_stops[
  , .(
    .N,
    median_distance_meters = qx(DISTANCE_METERS, 0.50),
    mean_seconds = mean(SECONDS_BETWEEN_STOPS),
    sd = sd(SECONDS_BETWEEN_STOPS),
    cvar = sd(SECONDS_BETWEEN_STOPS) / mean(SECONDS_BETWEEN_STOPS),
    p05 = qx(SECONDS_BETWEEN_STOPS, 0.05),
    p25 = qx(SECONDS_BETWEEN_STOPS, 0.25),
    p50 = qx(SECONDS_BETWEEN_STOPS, 0.50),
    p75 = qx(SECONDS_BETWEEN_STOPS, 0.75),
    p95 = qx(SECONDS_BETWEEN_STOPS, 0.95)
  ),
  by = .(FROM_STOP, STOP_ID)
]
gc()
bus_passenger_stops_summary <- bus_passenger_stops_summary[N > 30]
gc()
bus_passenger_stops_summary <- bus_passenger_stops_summary[order(-N)]
gc()
datatable(bus_passenger_stops_summary)
```

