# Generated by Django 2.0.1 on 2018-04-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('release_date', models.DateTimeField()),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('album', models.TextField()),
                ('writer', models.TextField()),
            ],
            options={
                'db_table': 'api_song',
                'ordering': ('release_date',),
                'managed': False,
            },
        ),
    ]
