# Generated by Django 2.2.1 on 2019-05-13 20:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BusAllStops',
            fields=[
                ('vehicle_id', models.IntegerField(blank=True, null=True)),
                ('opd_date', models.DateField(blank=True, null=True)),
                ('act_arr_time', models.DateTimeField(blank=True, null=True)),
                ('act_dep_time', models.DateTimeField(blank=True, null=True)),
                ('nom_arr_time', models.DateTimeField(blank=True, null=True)),
                ('nom_dep_time', models.DateTimeField(blank=True, null=True)),
                ('event_no_trip', models.IntegerField(blank=True, null=True)),
                ('meters', models.IntegerField(blank=True, null=True)),
                ('stop_id', models.IntegerField(blank=True, null=True)),
                ('stop_pos', models.IntegerField(blank=True, null=True)),
                ('distance_to_next', models.IntegerField(blank=True, null=True)),
                ('distance_to_trip', models.IntegerField(blank=True, null=True)),
                ('doors_opening', models.IntegerField(blank=True, null=True)),
                ('stop_type', models.IntegerField(blank=True, null=True)),
                ('door_open_time', models.IntegerField(blank=True, null=True)),
                ('geom_point_4326', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'bus_all_stops',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BusPassengerStops',
            fields=[
                ('vehicle_id', models.IntegerField(blank=True, null=True)),
                ('service_date', models.DateField(blank=True, null=True)),
                ('arrive_time', models.DateTimeField(blank=True, null=True)),
                ('leave_time', models.DateTimeField(blank=True, null=True)),
                ('stop_time', models.DateTimeField(blank=True, null=True)),
                ('route_number', models.IntegerField(blank=True, null=True)),
                ('direction', models.IntegerField(blank=True, null=True)),
                ('location_id', models.IntegerField(blank=True, null=True)),
                ('dwell', models.IntegerField(blank=True, null=True)),
                ('door', models.IntegerField(blank=True, null=True)),
                ('lift', models.IntegerField(blank=True, null=True)),
                ('ons', models.IntegerField(blank=True, null=True)),
                ('offs', models.IntegerField(blank=True, null=True)),
                ('estimated_load', models.IntegerField(blank=True, null=True)),
                ('train_mileage', models.FloatField(blank=True, null=True)),
                ('geom_point_4326', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'bus_passenger_stops',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BusTrips',
            fields=[
                ('vehicle_id', models.IntegerField(blank=True, null=True)),
                ('opd_date', models.DateField(blank=True, null=True)),
                ('act_dep_time', models.DateTimeField(blank=True, null=True)),
                ('act_end_time', models.DateTimeField(blank=True, null=True)),
                ('nom_dep_time', models.DateTimeField(blank=True, null=True)),
                ('nom_end_time', models.DateTimeField(blank=True, null=True)),
                ('event_no_trip', models.IntegerField(blank=True, null=True)),
                ('meters', models.IntegerField(blank=True, null=True)),
                ('line_id', models.IntegerField(blank=True, null=True)),
                ('pattern_direction', models.TextField(blank=True, null=True)),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'bus_trips',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RailPassengerStops',
            fields=[
                ('vehicle_id', models.IntegerField(blank=True, null=True)),
                ('service_date', models.DateField(blank=True, null=True)),
                ('arrive_time', models.DateTimeField(blank=True, null=True)),
                ('leave_time', models.DateTimeField(blank=True, null=True)),
                ('stop_time', models.DateTimeField(blank=True, null=True)),
                ('route_number', models.IntegerField(blank=True, null=True)),
                ('direction', models.IntegerField(blank=True, null=True)),
                ('location_id', models.IntegerField(blank=True, null=True)),
                ('dwell', models.IntegerField(blank=True, null=True)),
                ('door', models.IntegerField(blank=True, null=True)),
                ('lift', models.IntegerField(blank=True, null=True)),
                ('ons', models.IntegerField(blank=True, null=True)),
                ('offs', models.IntegerField(blank=True, null=True)),
                ('estimated_load', models.IntegerField(blank=True, null=True)),
                ('train_mileage', models.FloatField(blank=True, null=True)),
                ('geom_point_4326', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'rail_passenger_stops',
                'managed': False,
            },
        ),
    ]
