\copy init_cyclic_v1h from '/home/znmeb/Raw/transportation-2018/transit-operations-analytics-data/init_cyclic_v1h 1-30SEP2017.csv' with csv header
\copy init_cyclic_v1h from '/home/znmeb/Raw/transportation-2018/transit-operations-analytics-data/init_cyclic_v1h 1-31OCT2017.csv' with csv header
\copy init_cyclic_v1h from '/home/znmeb/Raw/transportation-2018/transit-operations-analytics-data/init_cyclic_v1h 1-30NOV2017.csv' with csv header
\copy init_cyclic_v1h from '/home/znmeb/Raw/transportation-2018/transit-operations-analytics-data/init_cyclic_v1h 1-30APR2018.csv' with csv header
\copy init_cyclic_v1h from '/home/znmeb/Raw/transportation-2018/transit-operations-analytics-data/init_cyclic_v1h 1-31MAY2018.csv' with csv header
\copy init_tripsh from '/home/znmeb/Raw/transportation-2018/transit-operations-analytics-data/init_tripsh 1-30SEP2017.csv' with csv header
\copy init_tripsh from '/home/znmeb/Raw/transportation-2018/transit-operations-analytics-data/init_tripsh 1-31OCT2017.csv' with csv header
\copy init_tripsh from '/home/znmeb/Raw/transportation-2018/transit-operations-analytics-data/init_tripsh 1-30NOV2017.csv' with csv header
\copy init_tripsh from '/home/znmeb/Raw/transportation-2018/transit-operations-analytics-data/init_tripsh 1-30APR2018.csv' with csv header
\copy init_tripsh from '/home/znmeb/Raw/transportation-2018/transit-operations-analytics-data/init_tripsh 1-31MAY2018.csv' with csv header
\copy init_veh_stoph from '/home/znmeb/Raw/transportation-2018/transit-operations-analytics-data/init_veh_stoph 1-30SEP2017.csv' with csv header
\copy init_veh_stoph from '/home/znmeb/Raw/transportation-2018/transit-operations-analytics-data/init_veh_stoph 1-31OCT2017.csv' with csv header
\copy init_veh_stoph from '/home/znmeb/Raw/transportation-2018/transit-operations-analytics-data/init_veh_stoph 1-30NOV2017.csv' with csv header
\copy init_veh_stoph from '/home/znmeb/Raw/transportation-2018/transit-operations-analytics-data/init_veh_stoph 1-30APR2018.csv' with csv header
\copy init_veh_stoph from '/home/znmeb/Raw/transportation-2018/transit-operations-analytics-data/init_veh_stoph 1-31MAY2018.csv' with csv header
\copy trimet_stop_event from '/home/znmeb/Raw/transportation-2018/transit-operations-analytics-data/trimet_stop_event 1-30SEP2017.csv' with csv header
\copy trimet_stop_event from '/home/znmeb/Raw/transportation-2018/transit-operations-analytics-data/trimet_stop_event 1-31OCT2017.csv' with csv header
\copy trimet_stop_event from '/home/znmeb/Raw/transportation-2018/transit-operations-analytics-data/trimet_stop_event 1-30NOV2017.csv' with csv header
\copy trimet_stop_event from '/home/znmeb/Raw/transportation-2018/transit-operations-analytics-data/trimet_stop_event 1-30APR2018.csv' with csv header
\copy trimet_stop_event from '/home/znmeb/Raw/transportation-2018/transit-operations-analytics-data/trimet_stop_event 1-31MAY2018.csv' with csv header
