FROM postgres:10
LABEL maintainer="M. Edward (Ed) Borasky <ed.borasky@hackoregon.org>"

# Install apt packages
RUN apt-get update \
  && apt-get install -qqy --no-install-recommends \
    postgis \
    postgresql-10-postgis-2.5 \
    postgresql-10-postgis-2.5-scripts \
    apt-utils \
  && apt-get clean

# set up automatic restores
COPY postgis-scripts/1make-dbusers.sh Backups/restore-all.sh /docker-entrypoint-initdb.d/
RUN chmod +x /docker-entrypoint-initdb.d/*.sh
COPY Backups /Backups
