---
title: "TOAD data exploration"
output: html_notebook
---

## Libraries
```{r}
library(data.table)

```

## Functions
```{r}
## quarter hour of day
qhod <- function(tstamp) {
  0.25 * trunc(4 * hour(tstamp) + minute(tstamp) / 15)
}

# five-number summary
qx <- function(x, p) {
    quantile(
      x, probs = p, na.rm = TRUE, names = FALSE
    )
}

```

## Vehicle stop history
Note: because this has to run in an 8GB laptop, we garbage-collect frequently
and avoid chaining / pipes.
```{r}
vehicle_stop_history <- fread("/csvs/raw_veh_stoph_2017_09.csv")
gc()
vehicle_stop_history <- vehicle_stop_history[
  !is.na(NOM_ARR_TIME) &
  !is.na(NOM_DEP_TIME) &
  !is.na(STOP_ID) &
  !is.na(GPS_LONGITUDE) &
  !is.na(GPS_LATITUDE)
]
gc()

```

## Stop events
```{r}
stop_events <- fread("/csvs/raw_stop_event_2017_09.csv")
gc()
stop_events <- stop_events[
  ROUTE_NUMBER >= 1 &
  ROUTE_NUMBER <= 291 &
  X_COORDINATE > 0 &
  Y_COORDINATE > 0
]
gc()

```

## Join the tables to get bus passenger stops
```{r}
vehicle_stop_history_by <- c(
  "OPD_DATE",
  "VEHICLE_ID",
  "ACT_ARR_TIME",
  "ACT_DEP_TIME",
  "STOP_ID"
)
setkeyv(vehicle_stop_history, vehicle_stop_history_by)
gc()
stop_events_by <- c(
  "SERVICE_DATE",
  "VEHICLE_NUMBER",
  "ARRIVE_TIME",
  "LEAVE_TIME",
  "LOCATION_ID"
)
setkeyv(stop_events, stop_events_by)
gc()
vehicle_stop_history <- merge(
  vehicle_stop_history, stop_events,
  by.x = vehicle_stop_history_by, by.y = stop_events_by,
  all = FALSE
)
rm(stop_events, stop_events_by)
gc()

```

## Date computations
```{r}
vehicle_stop_history <- vehicle_stop_history[
  , OPD_DATE := as.POSIXct(strptime(
    OPD_DATE, format = "%d%b%Y:%H:%M:%S", tz = "PST8PDT"
  ))
]
gc()
vehicle_stop_history <- vehicle_stop_history[
  , `:=`(
    NOM_ARR_TIME = OPD_DATE + NOM_ARR_TIME,
    ACT_ARR_TIME = OPD_DATE + ACT_ARR_TIME,
    NOM_DEP_TIME = OPD_DATE + NOM_DEP_TIME,
    ACT_DEP_TIME = OPD_DATE + ACT_DEP_TIME,
    YEAR = year(OPD_DATE),
    MONTH = month(OPD_DATE),
    DAY = mday(OPD_DATE),
    DAY_OF_WEEK = wday(OPD_DATE)
  )
]
gc()
vehicle_stop_history <- vehicle_stop_history[
  , QHOUR_OF_DAY := qhod(ACT_ARR_TIME)
]
gc()

```

## Lagged columns
```{r}
vehicle_stop_history_by <- c(
  "VEHICLE_ID",
  "ACT_ARR_TIME",
  "ACT_DEP_TIME",
  "STOP_ID"
)
setkeyv(vehicle_stop_history, vehicle_stop_history_by)
vehicle_stop_history <- vehicle_stop_history[
  , `:=`(
    FROM_STOP = shift(STOP_ID),
    METERS_TRAVELED = METERS - shift(METERS),
    SECONDS_TRAVELED = as.integer(ACT_ARR_TIME - shift(ACT_DEP_TIME)),
    ARRIVING_LOAD = shift(ESTIMATED_LOAD),
    SECONDS_LATE = as.integer(ACT_ARR_TIME - NOM_ARR_TIME)
  ),
  by = EVENT_NO_TRIP
]
gc()
vehicle_stop_history <- vehicle_stop_history[!is.na(FROM_STOP)]

```
## Primitive summary
```{r}
stop_to_stop_seconds <- vehicle_stop_history[
  , .(
    .N,
    p05 = qx(SECONDS_TRAVELED, 0.05),
    p25 = qx(SECONDS_TRAVELED, 0.25),
    p50 = qx(SECONDS_TRAVELED, 0.50),
    p75 = qx(SECONDS_TRAVELED, 0.75),
    p95 = qx(SECONDS_TRAVELED, 0.95)
  ),
  by = .(FROM_STOP, STOP_ID)
]
gc()
stop_to_stop_seconds <- stop_to_stop_seconds[order(-N)]
gc()
stop_to_stop_meters <- vehicle_stop_history[
  , .(
    .N,
    p05 = qx(METERS_TRAVELED, 0.05),
    p25 = qx(METERS_TRAVELED, 0.25),
    p50 = qx(METERS_TRAVELED, 0.50),
    p75 = qx(METERS_TRAVELED, 0.75),
    p95 = qx(METERS_TRAVELED, 0.95)
  ),
  by = .(FROM_STOP, STOP_ID)
]
gc()
stop_to_stop_meters <- stop_to_stop_meters[order(-N)]
gc()

```

