# Generated by Django 2.0.1 on 2018-06-12 05:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='POI',
            fields=[
                ('pk_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('description2_txt', models.CharField(max_length=60)),
                ('wkb_geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'db_table': 'POI_view',
                'managed': False,
            },
        ),
    ]
