# Generated by Django 2.0.1 on 2018-06-13 23:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic_sandbox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisasterNeighborhoodView',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('wkb_geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('pgd_landslide_dry_mean_di', models.CharField(max_length=50)),
                ('pgd_total_wet_mean_di', models.CharField(max_length=50)),
                ('pgv_site_mean_mmi_txt', models.CharField(max_length=10)),
                ('pgv_site_mean_desc', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'disaster_neighborhood_view',
                'managed': False,
            },
        ),
    ]
