# Generated by Django 2.0.12 on 2019-04-09 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civic_sandbox', '0003_auto_20190327_0752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages',
            name='default_foundation',
        ),
        migrations.RemoveField(
            model_name='packages',
            name='default_slide',
        ),
        migrations.RemoveField(
            model_name='packages',
            name='foundations',
        ),
        migrations.RemoveField(
            model_name='packages',
            name='slides',
        ),
        migrations.DeleteModel(
            name='Foundation',
        ),
        migrations.DeleteModel(
            name='Packages',
        ),
        migrations.DeleteModel(
            name='Slide',
        ),
    ]
