# Generated by Django 2.0.1 on 2018-06-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_address_basicearthquakeemergencycommunicationnodebeecnlocations_firesta_majorriverbridges_neighborho'),
    ]

    operations = [
        migrations.CreateModel(
            name='POI',
            fields=[
                ('ogc_fid', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('description_txt', models.CharField(blank=True, max_length=255, null=True)),
                ('description2_txt', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=5, null=True)),
                ('wkb_geometry', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'POI_view',
                'managed': False,
            },
        ),
    ]
