# Generated by Django 2.0.1 on 2018-06-21 01:22

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_disasterneighborhoods_disasterneighborhoodview'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisasterNeighborhoodGrid',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('centroidx', models.CharField(blank=True, max_length=255, null=True)),
                ('centroidy', models.CharField(blank=True, max_length=255, null=True)),
                ('x_simple', models.CharField(blank=True, max_length=255, null=True)),
                ('y_simple', models.CharField(blank=True, max_length=255, null=True)),
                ('wkb_geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('pgv_site_count', models.CharField(blank=True, max_length=255, null=True)),
                ('pgv_site_max', models.CharField(blank=True, max_length=255, null=True)),
                ('pgv_site_mean', models.CharField(blank=True, max_length=255, null=True)),
                ('pgv_site_min', models.CharField(blank=True, max_length=255, null=True)),
                ('pgv_site_std', models.CharField(blank=True, max_length=255, null=True)),
                ('pgd_landslide_dry_count', models.CharField(blank=True, max_length=255, null=True)),
                ('pgd_landslide_dry_max', models.CharField(blank=True, max_length=255, null=True)),
                ('pgd_landslide_dry_mean', models.CharField(blank=True, max_length=255, null=True)),
                ('pgd_landslide_dry_min', models.CharField(blank=True, max_length=255, null=True)),
                ('pgd_landslide_dry_std', models.CharField(blank=True, max_length=255, null=True)),
                ('pgd_landslide_wet_count', models.CharField(blank=True, max_length=255, null=True)),
                ('pgd_landslide_wet_max', models.CharField(blank=True, max_length=255, null=True)),
                ('pgd_landslide_wet_mean', models.CharField(blank=True, max_length=255, null=True)),
                ('pgd_landslide_wet_min', models.CharField(blank=True, max_length=255, null=True)),
                ('pgd_landslide_wet_std', models.CharField(blank=True, max_length=255, null=True)),
                ('pgd_liquefaction_wet_count', models.CharField(blank=True, max_length=255, null=True)),
                ('pgd_liquefaction_wet_max', models.CharField(blank=True, max_length=255, null=True)),
                ('pgd_liquefaction_wet_mean', models.CharField(blank=True, max_length=255, null=True)),
                ('pgd_liquefaction_wet_min', models.CharField(blank=True, max_length=255, null=True)),
                ('pgd_liquefaction_wet_std', models.CharField(blank=True, max_length=255, null=True)),
                ('pgd_total_wet_mean', models.CharField(blank=True, max_length=255, null=True)),
                ('pgv_site_min_mmi', models.IntegerField(blank=True, null=True)),
                ('pgv_site_max_mmi', models.IntegerField(blank=True, null=True)),
                ('pgv_site_mean_mmi', models.IntegerField(blank=True, null=True)),
                ('pgd_landslide_dry_min_di', models.CharField(blank=True, max_length=255, null=True)),
                ('pgd_landslide_dry_max_di', models.CharField(blank=True, max_length=255, null=True)),
                ('pgd_landslide_dry_mean_di', models.CharField(blank=True, max_length=255, null=True)),
                ('pgd_landslide_wet_min_di', models.CharField(blank=True, max_length=255, null=True)),
                ('pgd_landslide_wet_max_di', models.CharField(blank=True, max_length=255, null=True)),
                ('pgd_landslide_wet_mean_di', models.CharField(blank=True, max_length=255, null=True)),
                ('pgd_liquefaction_wet_min_di', models.CharField(blank=True, max_length=255, null=True)),
                ('pgd_liquefaction_wet_max_di', models.CharField(blank=True, max_length=255, null=True)),
                ('pgd_liquefaction_wet_mean_di', models.CharField(blank=True, max_length=255, null=True)),
                ('pgd_total_wet_mean_di', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'disaster_neighborhood_grid',
                'managed': False,
            },
        ),
    ]
